GET http://localhost:8000/A
Accept: application/json

###
POST http://localhost:8000/api/shorten
Content-Type: application/json

{
  "url": "www.example.com",
  "expiration_in_minutes": 0
}

###
POST http://localhost:8000/api/shorten
Content-Type: application/json

{
  "url": "www.example.com",
  "expiration_in_minutes": -1
}

###
