GET http://localhost:8000/2
Accept: application/json

###
GET http://localhost:8000/api/info?shortlink=2
Accept: application/json

###
POST http://localhost:8000/api/shorten
Content-Type: application/json

{
  "url": "https://www.example.com",
  "expiration_in_minutes": 0
}

###
POST http://localhost:8000/api/shorten
Content-Type: application/json

{
  "url": "https://www.example.com",
  "expiration_in_minutes": -1
}

###
